### ISSUE TITLE
Préparer les slides pour la partie mult-host : swarm, kubernetes

### ISSUE THREAD

**Issue by l0rd** [Zenika/NC-Docker-Avance#4]

**Comment by vdemeester** [comment]
Pour swarm, voir dans `Hands-on/supports/swarm/` pour faire le setup (scripts, etc..), j'ai commencé un script de setup qui marche presque (juste la dernière étape qui chie faut que je vois pourquoi..). Il reste :
1. Faire joujou avec (des commandes à lancer, documenter dans un fichier texte, ou script ?)
2. Démarrer un registry local également pour optimiser le tout (chaque node télécharge à nouveau l'image swarm)

**Comment by vdemeester** [comment]
Et voilà j'ai compléter en mettant un hostname lisible pour chaque nœud et des commandes exemple, je continue à compléter aujourd'hui :-).
